### ISSUE TITLE
L'ajout de source ne fonctionne pas

### ISSUE THREAD

**Issue by Biocef** [Akylas/conty#7]
Bonjour,
J'ai testé l'ajout de source mais malheureusement ça ne fonctionne pas du tout.

En mettant n'importe quoi en adresse de source (par exemple http://1.2.3.4), ça va chercher les histoires de "Raconte moi une histoire", même si cette source n'est pas installée.

Conty ne cherche même pas à joindre l'adresse renseignée (quelle qu'elle soit), il ne communique qu'avec les adresses cdn.discordapp.com et gist.githubusercontent.com lorsqu'on fait une recherche d'histoires sur la nouvelle source ajoutée. 

Cordialement.

**Comment by farfromrefug** [comment]
@Biocef Désolé pour ce probleme. Je vais regarder ca. Tu peux me partager l'url que tu testes?

**Comment by Biocef** [comment]
Merci !
J'utilise une ip locale, mes enfant n'ont pas accès à internet sur leur téléphone.
Mais quelle que soit l'ip renseignée, Conty ne cherche pas à y accéder.
Quand je regarde les communications sortantes de Conty, au lieu d'aller voir l'adresse renseignée, l'appli communique juste avec l'adresse de la source "Racontes moi une histoire" (même si elle n'est pas installée) et va chercher ces histoires là même si ce n'est pas ce qu'on lui demande.

**Comment by farfromrefug** [comment]
OK je corrige ca cette aprem

**Comment by farfromrefug** [comment]
@Biocef nouvelle version dispo sur github. Je lance la publication sur le store

**Comment by Biocef** [comment]
Super, merci !!
Il y a une syntaxe particulière à respecter pour les objets du json ?

**Comment by farfromrefug** [comment]
@Biocef oui ca attends le meme format que le json de RMUH. Voila un exemple https://github.com/Akylas/conty/blob/main/test_data/source.json

**Comment by Biocef** [comment]
Parfait, merci beaucoup, je teste ça une fois la maj faite.

**Comment by Biocef** [comment]
J'ai testé, ça marche parfaitement bien ! 👍 
Une dernière question tant que j'y suis : 
Dans mon json, quand je fais pointer l'url de "download" directement vers le .zip d'une histoire ça ne fonctionne pas. 
Pour que ça fonctionne je dois faire pointer l'url de "download" vers une page web contenant l'adresse du .zip.
Il y a la possibilité de faire en sorte que l'installation de l'histoire se fasse tout de suite quand on clique dessus si le json fait pointer directement vers un zip ?
Plutôt que de devoir créer un .html pour chaque histoire ce serait plus pratique.

**Comment by farfromrefug** [comment]
@Biocef pas de soucis je corrige ca de suite!

**Comment by farfromrefug** [comment]
@Biocef c'est publié sur Github. Ca arrive bientot sur le store

**Comment by Biocef** [comment]
Merci c'est parfait ! 🥇

**Comment by farfromrefug** [comment]
@Biocef je vois des erreurs qui me semble lies a toi (des erreurs de telechargement de pack depuis une source sur un reseau local). L'app marche pour toi?

**Comment by farfromrefug** [comment]
@Biocef c etait peut etre pas le zip le.probleme mais peut être la structure des fichiers compressés dedans. Pas sur...
En tout cas cool

**Comment by Biocef** [comment]
Non, la structure est bonne, en decompressant via windows j'ai bien : 
Dossier histoire, dedans fichier json + dossier assets dans lequel j'ai fichier.mp3
Quand je décompresse sur le tel j'ai : 
Dossier histoire, dedans fichier json + un fichier qui s'appelle assets\fichier.mp3 (et aucun dossier)
Bref bizarre mais via 7zip plus de soucis.

Rien à voir mais pour info, les zip des histoires installées ne se suppriment pas du dossier "cache" de l'application, même quand l'histoire est supprimée.

**Comment by farfromrefug** [comment]
@Biocef bon point je vais les supprimer. Mais je pense qu ils sont supprimes au redémarrage
